dist: trusty
language: python
addons:
  sonarcloud:
    organization: "borisv13-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
python:
  - "3.6"

install:
  - pip install -r requirements.txt
script:
  - py.test  --cov-report term --cov=.
  - coverage xml
  - sonar-scanner
services:
  - sqlite
  - sonar-scanner
env:
  - DJANGO=2.2.6
after_success:
  - codecov


